version: "3.8"

services: 
  postgres:
    image: postgres:15-alpine
    container_name: bookstore-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bookstore-network

volumes:
  postgres-data:

networks:
  bookstore-network:
    driver: bridge
